services:
  app:
    build: .
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
     - ./mega_urls.json:/main/mega_urls.json
     - ./mega_urls.json:/main/ebs_urls.json
     - ./app:/main/app
    working_dir: /main/app
    expose:
      - "8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/main


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
